name: Release Pipeline 
on:
  workflow_dispatch:

env:
  rg-name: "mayur-rg"
  adf-name: "mayur-dev-adf-poc"
  target-adf: "mayur-prod-adf-poc"
permissions:
  id-token: write  
  contents: write
  actions: read

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: ExportedArmTemplate
      
      - name: Login via Az module
        uses: Azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 
      
      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ env.rg-name}}
          dataFactoryName: ${{ env.target-adf}}
          armTemplateFile: ARMTemplateForFactory.json
          armTemplateParametersFile: ARMTemplateParametersForFactory.json 
